
- name: generate ssh cmd tasks
  set_fact:
    ssh_cmd: "eval `ssh-agent` >/dev/null; trap \"ssh-agent -k\" EXIT; ssh-add - <<< \"${PRIVATE_KEY}\" ; ssh -o StrictHostKeyChecking=no {{ login }}@{{ pycomps_endpoint }} \"{{ ssh_cmd_to_run }}\""


- name: print ssh cmd
  debug:
    var: ssh_cmd
