- name: Submit PyCOMPs Job
  hosts: all
  strategy: free
  tasks:

    - name: Set compss_module_version
      set_fact:
        compss_module_version: "{{ compss_module_version_input }}"
      when:
        - compss_module_version_input is defined
        - compss_module_version_input | length > 0

    - name: Set num_nodes
      set_fact:
        num_nodes: "{{ num_nodes_input }}"
      when:
        - num_nodes_input is defined
        - num_nodes_input | length > 0

    - name: Set input_data_path
      set_fact:
        input_data_path: "{{ input_data_path_input }}"
      when:
        - input_data_path_input is defined
        - input_data_path_input | length > 0

    - name: Set output_data_path
      set_fact:
        output_data_path: "{{ output_data_path_input }}"
      when:
        - output_data_path_input is defined
        - output_data_path_input | length > 0

    - name: Override container_image by transferred_container_image
      set_fact:
        container_image: "{{ transferred_container_image }}"
      when:
        - transferred_container_image is defined
        - transferred_container_image | length > 0

    - name: Set container_image
      set_fact:
        extra_compss_opts: "{{ extra_compss_opts }} --container_image={{ container_image }}"
      when:
        - container_image is defined
        - container_image | length > 0

    - name: Set container_compss_path
      set_fact:
        extra_compss_opts: "{{ extra_compss_opts }} --container_compss_path={{ container_compss_path }}"
      when:
        - container_compss_path is defined
        - container_compss_path | length > 0

    - name: Set container_opts
      set_fact:
        extra_compss_opts: "{{ extra_compss_opts }} --container_opts={{ container_opts }}"
      when:
        - container_opts is defined
        - container_opts | length > 0

    - name: Set python_interpreter
      set_fact:
        extra_compss_opts: "{{ extra_compss_opts }} --python_interpreter={{ python_interpreter }}"
      when:
        - python_interpreter is defined
        - python_interpreter | length > 0

    - name: Set qos
      set_fact:
        extra_compss_opts: "{{ extra_compss_opts }} --qos={{ qos }}"
      when:
        - qos is defined
        - qos | length > 0

    - name: generate ssh cmd tasks
      set_fact:
        ssh_cmd_to_run: "module load COMPSs/{{ compss_module_version }}; module load compss/{{ compss_module_version }}; module load singularity; enqueue_compss {{ extra_compss_opts | default('') }} -d --num_nodes={{ num_nodes }} {{ command }}"

    - name: generate ssh cmd args
      set_fact:
        ssh_cmd_to_run: "{{ ssh_cmd_to_run }} {{ item }}"
      loop: "{{ arguments }}"
      when: arguments | length > 0

    - name: generate ssh command
      import_tasks: generate_ssh_cmd_tasks.yml

    - name: submit job
      shell: "{{ ssh_cmd }} 2>&1 | grep 'Submitted batch job' | tr -d 'Submitted batch job'"
      args:
        executable: /bin/bash
      environment:
        INPUT_DATA_PATH: "{{ input_data_path }}"
        OUTPUT_DATA_PATH: "{{ output_data_path }}"
        PRIVATE_KEY: "{{ key }}"
      register: ssh_output

    - name: Set job id
      set_fact:
        TOSCA_JOB_ID: "{{ ssh_output.stdout_lines[0] }}"