tosca_definitions_version: alien_dsl_3_0_0


metadata:
  template_name: pycomps.ansible
  template_version: 1.0.0-SNAPSHOT
  template_author: loicalbertin


imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - alien-base-types:3.0.0
  - yorc-types:1.1.0

node_types:
  pycomps.ansible.nodes.PyCOMPSJob:
    derived_from: org.alien4cloud.nodes.Job
    metadata:
      icon: COMPSs-logo.png
    properties:
      pycomps_endpoint:
        type: string
        description: The endpoint of the pycomps server
        required: true
      num_nodes:
        type: integer
        required: false
        default: 1
      data_path:
        type: string
        required: false
        default: ""
      command:
        type: string
        required: true
      arguments:
        type: list
        required: false
        entry_schema:
          description: list of arguments
          type: string
    interfaces:
      tosca.interfaces.node.lifecycle.Runnable:
        inputs:
          pycomps_endpoint: { get_property: [ SELF, pycomps_endpoint ] }
          login: { get_input: user_id }
          key: { get_vault_secret: [ concat: ["/secret/data/ssh-credentials/", get_input: vault_id ], data=privateKey] }
        submit:
          inputs:
            num_nodes: { get_property: [ SELF, num_nodes ] }
            num_nodes_input: { get_input: [ num_nodes ] }
            command: { get_property: [ SELF, command ] }
            arguments: { get_property: [ SELF, arguments ] }
            data_path: { get_property: [ SELF, data_path ] }
            data_path_input: { get_input: target_path }
          implementation: playbooks/submit_pycomps.yaml
        run: playbooks/monitor_pycomps.yaml

