tosca_definitions_version: alien_dsl_3_0_0


metadata:
  template_name: pycomps.ansible
  template_version: 1.0.0-SNAPSHOT
  template_author: loicalbertin


imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - alien-base-types:3.0.0
  - yorc-types:1.1.0

node_types:
  pycomps.ansible.nodes.PyCOMPSJob:
    derived_from: org.alien4cloud.nodes.Job
    metadata:
      icon: COMPSs-logo.png
    properties:
      pycomps_endpoint:
        type: string
        description: The endpoint of the pycomps server
        required: true
      compss_module_version:
        type: string
        required: false
        default: "2.10"
      num_nodes:
        type: integer
        required: false
        default: 1
      qos:
        type: string
        required: false
        default: debug
      input_data_path:
        type: string
        required: false
        default: "/tmp"
      output_data_path:
        type: string
        required: false
        default: "/tmp"
      command:
        type: string
        required: true
      arguments:
        type: list
        required: false
        entry_schema:
          description: list of arguments
          type: string
      container_image:
        type: string
        required: false
        default: ""
      container_compss_path:
        type: string
        required: false
        default: ""
      container_opts:
        type: string
        required: false
        default: ""
      python_interpreter:
        type: string
        required: false
        default: ""
      extra_compss_opts:
        type: string
        required: false
        default: ""
    interfaces:
      tosca.interfaces.node.lifecycle.Runnable:
        inputs:
          pycomps_endpoint: { get_property: [ SELF, pycomps_endpoint ] }
          login: { get_input: user_id }
          key: { get_vault_secret: [ concat: ["/secret/data/ssh-credentials/", get_input: vault_id ], data=privateKey] }
        submit:
          inputs:
            compss_module_version: { get_property: [ SELF, compss_module_version ] }
            compss_module_version_input: { get_input: [ compss_module_version ] }
            num_nodes: { get_property: [ SELF, num_nodes ] }
            num_nodes_input: { get_input: [ num_nodes ] }
            qos: { get_property: [ SELF, qos ] }
            command: { get_property: [ SELF, command ] }
            arguments: { get_property: [ SELF, arguments ] }
            input_data_path: { get_property: [ SELF, input_data_path ] }
            input_data_path_input: { get_input: target_path }
            output_data_path: { get_property: [ SELF, output_data_path ] }
            output_data_path_input: { get_input: source_path }
            container_image: { get_property: [ SELF, container_image ] }
            container_compss_path: { get_property: [ SELF, container_compss_path ] }
            container_opts: { get_property: [ SELF, container_opts ] }
            python_interpreter: { get_property: [ SELF, python_interpreter ] }
            extra_compss_opts: { get_property: [ SELF, extra_compss_opts ] }
          implementation: playbooks/submit_pycomps.yaml
        run: playbooks/monitor_pycomps.yaml

